export const ACTIVITY_TYPES = {
  TASK_CREATED: 'TASK_CREATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  TITLE_CHANGED: 'TITLE_CHANGED',
  DESCRIPTION_CHANGED: 'DESCRIPTION_CHANGED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  DUE_DATE_CHANGED: 'DUE_DATE_CHANGED',
  ASSIGNEE_CHANGED: 'ASSIGNEE_CHANGED',
  REPORTER_CHANGED: 'REPORTER_CHANGED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  COMMENT_DELETED: 'COMMENT_DELETED',
  MENTIONED_IN_COMMENT: 'MENTIONED_IN_COMMENT',
  COMMENT_REPLIED: 'COMMENT_REPLIED',
  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  ATTACHMENT_REMOVED: 'ATTACHMENT_REMOVED',
  BOARD_CREATED: 'BOARD_CREATED',
  BOARD_MEMBER_ADDED: 'BOARD_MEMBER_ADDED',
  BOARD_MEMBER_REMOVED: 'BOARD_MEMBER_REMOVED',
  ROLE_CHANGED: 'ROLE_CHANGED',
  TASK_REMINDER: 'TASK_REMINDER'
} as const;

export type ActivityType = keyof typeof ACTIVITY_TYPES;
